### DISCUSSION TITLE
Gallery

### DISCUSSION THREAD

**Discussion by mikke89** [mikke89/RmlUi#184] [Show and tell]
Every UI library needs a gallery!

I started adding some screenshots in the documentation:
https://mikke89.github.io/RmlUiDoc/pages/gallery.html
And the idea is to put all or some of these in the `Readme` here. 

Ideally, we want something that showcases various parts of the library, and looks nice at the same time. Although, I'm not sure if all of those examples look too good?

Perhaps you're using RmlUi in a project yourself, and you'd be willing to share screenshots? Then please add them here with a reply :) 
It would also be nice to have some links to projects using RmlUi, so if you'd like you can leave a link with your screenshots and I'll add them to the gallery.

**Comment by viciious** [comment]
How about providing some gifs with animation? Sorta like you did in this PR: https://github.com/libRocket/libRocket/pull/295

**Comment by viciious** [comment]
Warsow/Warfork both use libRocket for its UI but it's definitely not something to write home about..

**Comment by mikke89** [comment]
Yeah more gifs would be good, we could add those examples in there. I don't have much more to show for animations though.

Examples like Warsow/Warfork are nice, although I think it makes more sense to include projects using RmlUi or derivatives.

**Comment by viciious** [comment]
> Yeah more gifs would be good, we could add those examples in there. I don't have much more to show for animations though.
> 

Speaking of which, a simplified version of the "gridlock traffic simulator" UI would make a nice animations example. The problem with the current example is that it's a bit too simplistic, while the gifs showcase menu transitions between multiple documents. The first thing that springs to my mind when I see these is "whoa, how do I do that?" but there's no actual code samples.

**Comment by Unicornum** [comment]
My hands haven’t reached RmlUi yet, I'm still using the old version (libRocket), but maybe you will find something useful: http://unicornum.github.io/Covellitepp/index.html

**Comment by mikke89** [comment]
@Unicornum Thanks, looks like some nice examples. I'd prefer that the gallery only showed examples from RmlUi, so let me know if you upgrade. :)
I'd also be interested to hear how compiling RmlUi for Android goes, I haven't tried that myself.

**Comment by Unicornum** [comment]
> @Unicornum Thanks, looks like some nice examples. I'd prefer that the gallery only showed examples from RmlUi, so let me know if you upgrade. :)
> I'd also be interested to hear how compiling RmlUi for Android goes, I haven't tried that myself.

I switched my framework to using RmlUi (v3.2), everything is fine, loading time and occupied memory decreased by 3-5 times, on Android (NDK r16b) everything also works fine.

**Comment by mikke89** [comment]
@Unicornum Great to hear, nice to see the performance improvements. I'd be happy to add some of the screenshots to the RmlUi gallery if you'd like :)

**Comment by Unicornum** [comment]
> @Unicornum Great to hear, nice to see the performance improvements. I'd be happy to add some of the screenshots to the RmlUi gallery if you'd like :)

Take what you see fit :)

**Comment by reven86** [comment]
Hello!

I've replaced all UI in my [iOS](https://apps.apple.com/app/armor-inspector-wot-pc-blitz/id905734645), [Android](https://play.google.com/store/apps/details?id=com.dreamfarmgames.wot.armorinspector.android2) and [web](https://armor.wotinspector.com/en/pc/12305-e-50-ausf-m/) app with RmlUI and I'm very happy with results! It is a tool for World of Tanks players helping to learn and understand game mechanics.

Tech stack:
- C++/OpenGL 3.0 working on quite old and heavily customized Gameplay3D engine.
- two UI contexts: for 2D UI and for tooltips on 3D scene.
- UI scripting with Lua
- SVG icons
- custom shaders for images
- hot reload environment for RmlUI and Lua scripts

Some screenshots below:
<img width="960" height="640" alt="ai_4 0 0_960x640_2018-06-24_05-52-44 (1)" src="https://github.com/user-attachments/assets/2c4a2160-5c21-4389-8c55-6d64bc46c7c9" />
<img width="960" height="640" alt="ai_4 0 0_960x640_2025-11-24_16-18-18" src="https://github.com/user-attachments/assets/69644844-2f9b-4440-8b9f-bd8317ef3064" />
<img width="960" height="640" alt="ai_4 0 0_960x640_2025-11-24_16-31-06" src="https://github.com/user-attachments/assets/205e3a81-6a8e-4ef8-9804-b3cea5b40c6f" />
<img width="960" height="640" alt="ai_4 0 0_960x640_2025-11-24_16-33-54" src="https://github.com/user-attachments/assets/9645d04b-d14d-4351-a88f-7dd5fbab1d2b" />
<img width="960" height="640" alt="ai_4 0 0_960x640_2025-11-24_16-44-14" src="https://github.com/user-attachments/assets/5de89c3c-6a61-4269-8f62-14e79cb6e42c" />
<img width="960" height="640" alt="ai_4 0 0_960x640_2025-11-24_16-39-42" src="https://github.com/user-attachments/assets/c1eab714-3a44-4c83-9692-11e5cda92c49" />

**Reply by mikke89** [reply]
Oh, wow, that's really impressive. Quite an advanced UI use case. Very cool, thanks a lot for sharing! I'll happily put some screenshots up in the gallery if you don't mind :)

Seems like the webassembly is working well here. I'm interested to hear more about your custom shaders for images, how is this working if I may ask?

Are you using the new touch events, is that working well for you?

**Reply by reven86** [reply]
I'll be glad if you put screenshots in the gallery!

Yes, webassembly is working well, however I don't directly use the provided OpenGL backend and used it as a reference in porting RmlUI to GamePlay3D engine. As for custom shaders, I reworked RenderInterface::LoadTexture method to accept not only textures, but materials. Materials are render states and samplers bound to vertex and fragment shaders, e.g.:

```
material:

  renderState:
    blend: true
    blendSrc: ONE
    blendDst: ONE_MINUS_SRC_ALPHA

  u_maxDamageDistance: HEATMAP_MAX_DAMAGE_DISTANCE
  u_vehicleAngles: VEHICLE_ANGLES

  u_classHeatmaps: HEATMAP_GROUND_CLASS_HEATMAPS
  u_maxWeightInvLog: HEATMAP_GROUND_MAX_WEIGHT_INV_LOG
  
  u_damagePoint: HEATMAP_DAMAGE_POINT
  u_trajectoryPosition: TRAJECTORY_LOCAL_POSITION
  u_dotColor: PALETTE_colorUIActive

  technique:
  - id: default
    pass:
      defines: "UI_RENDER"
      vertexShader: rml/shaders/shader_vert_main.vert
      fragmentShader: shaders/ground_heatmap.frag
  
  - id: impacts
    sampler:
    - id: u_heatmapGradient
      path: materials/vehicle/heatmap_gradient.png
      mipmap: false
      wrapS: CLAMP
      wrapT: CLAMP
      minFilter: LINEAR
      magFilter: LINEAR

    pass:
      defines: "UI_RENDER;IMPACTS"
      vertexShader: rml/shaders/shader_vert_main.vert
      fragmentShader: shaders/ground_heatmap.frag
```

It is more flexible to use materials instead of just textures to render things, because it will allow you to use any shader and not being dependent on just textures: you can have shaders with multiple textures or no textures at all.

In the .rml code I just write the regular `<img>` tag pointing to material and technique if needed:
`<img id="damage_minimap" class="mx-auto" src="materials/ground_heatmap.material#impacts" width="160dp" height="160dp"/>`

And if you pass regular texture to `<img>` it will wrap it into default alpha blend material. All default rml shaders were also rewritten using material system and with this approach the RenderInterface::CompileShader method just return the predefined materials for built-in shaders (gradients). Both Rml::CompiledShaderHandle and Rml::TextureHandle reference the Material class:

```
	if (name == "linear-gradient")
	{
		material = gameplay::Material::create("rml/materials/rml_gradient.material");

		const bool repeating = Rml::Get(parameters, "repeating", false);
		material->getParameter("_func")->setInt(static_cast<int>(repeating ? ShaderGradientFunction::RepeatingLinear : ShaderGradientFunction::Linear));

		Rml::Vector2f p = Rml::Get(parameters, "p0", Rml::Vector2f(0.f));
		Rml::Vector2f v = Rml::Get(parameters, "p1", Rml::Vector2f(0.f)) - p;

		material->getParameter("_p")->setVector2(gameplay::Vector2(p.x, p.y));
		material->getParameter("_v")->setVector2(gameplay::Vector2(v.x, v.y));
		ApplyColorStopList(material, parameters);
	}
```

As for touch events, it was the reason I made a pull request. I just needed scrolling to work on mobile phones. It works fine, however, sometimes there is an issue that when you release a finger after scrolling it fires onclick event on the element beneath. It is a minor issue for me and I didn't investigate it further, but most likely it is related to whether the press and release events happen on the same element during scrolling.
