### DISCUSSION TITLE
Element with border-radius style has sawtooth

### DISCUSSION THREAD

**Discussion by xland** [mikke89/RmlUi#384] [General]
Element with `border-radius` style has sawtooth

Windows 10  4k screen

![image](https://user-images.githubusercontent.com/2980915/205593725-a2f7c9d5-0c00-4c57-8588-e8e7d4ac176c.png)

```css
#installBtn {
  border-radius: 6px;
  padding-left: 26dp;
  padding-right: 26dp;
  text-align: center;
  width: 180dp;
  height: 50dp;
  line-height: 50dp;
  background: #1890ff;
  color: #fff;
  margin-left: auto;
  margin-right: auto;
  font-size: 22dp;
}

#installBtn:hover {
  background-color: #096dd9;
}
```
