### ISSUE TITLE
select option:hover does not work reliably.

### ISSUE THREAD

**Issue by rokups** [mikke89/RmlUi#119]
I use following style:
```css
select selectbox option:hover
{
    text-decoration: underline;
}
```
Very first time i interact with select everything works as expected:
![image](https://user-images.githubusercontent.com/19151258/91942464-aa88d380-ed03-11ea-9195-5efa97f7903e.png)

After option is selected or dropdown is closed and reopened - underline effect no longer appears. Element functions properly otherwise.
![image](https://user-images.githubusercontent.com/19151258/91942554-cee4b000-ed03-11ea-834d-ef22bf54d419.png)
