### ISSUE TITLE
absolutely positioned elements get clipped when they shouldnt

### ISSUE THREAD

**Issue by rokups** [mikke89/RmlUi#123]
Gif displays bottom of the window with a translucent dark resize handle at the bottom-right corner. When window is resized vertically resize handle gets clipped even if it's z-index is set high.
![clipping](https://user-images.githubusercontent.com/19151258/94255760-6cad5280-ff31-11ea-913d-d39a80835836.gif)

```css
.resize-handle
{
    position: absolute;
    width: 16dp;
    height: 16dp;
    bottom: -1dp;
    right: 0;
    cursor: resize;
    background: #000000;
    opacity: 0.1;
    border-top-left-radius: 999dp;
    z-index: 999;
}
```

```html
<template name="window" content="content">
<head>
	<link type="text/rcss" href="rml.rcss"/>
	<link type="text/rcss" href="default.rcss"/>
</head>
<body id="window">
    <div id="titlebar">
        <handle move_target="#document">
            <div id="title">Title</div>
            <button class="close-window" onclick="{'e': 'CloseWindow'}"></button>
        </handle>
    </div>
    <div id="content">
    </div>
    <handle size_target="#document" class="resize-handle"></handle> <!-- here -->
</body>
</template>
```
