### ISSUE TITLE
Issue with buttons

### ISSUE THREAD

**Issue by Unknownprk** [mikke89/RmlUi#292]
Hey! I seem to be having some issues with button alignments in relation to other elements like input text field, there seems to be some kind of "hidden" margin on the top of the buttons

![image](https://user-images.githubusercontent.com/67846685/160155923-47f9b583-2380-439a-b152-7dd520592f23.png)

Unsure if this is an issue with the buttons or the input field

RML:
```HTML
<div>
  <button>All</button>
  <button>Button</button>
  <button>Button</button>
  <button>Button</button>
  <button>Button</button>
  <button>Button</button>
  <input type="text"/>
</div>
```

CSS:
```CSS
button {
  background: #021e27;
  margin-left: 0.2em;
  padding: 0.2em 0.5em 0.2em 0.5em;
  color: white;
}

input {
  background: #021e27;
  margin-left: 0.2em;
  padding: 0.2em 0.5em 0.2em 0.5em;
  color: white;
}
```

**Comment by mikke89** [comment]
Hi!

One thing to consider here is that the input element is a replaced element. This is layed out differently from how buttons are layed out (buttons aren't anything special in RML, just normal inline elements). So I wouldn't really expect them to line up like that. Instead, replaced elements are lined up such that their bottom lines up with the baseline, it seems this is exactly what is happening in your screenshot.

We might try to calculate a better baseline for input elements so that its text lines up with the baseline of the buttons. However, this would not be a guarantee that the outline of the elements would also line up, which is what I think is your desired result.

Instead, you could try to add something like this:
```css
button, input {
	height: 1.2em;
	display: inline-block;
	vertical-align: bottom;
}
```
