### ISSUE TITLE
Weird sizing of the `select` element.

### ISSUE THREAD

**Issue by AmaiKinono** [mikke89/RmlUi#666]
I think I've found some strange behavior of the `select` element, but I'm new to this library (and C++) so please point out if I did anything wrong.

The test is done by creating a new example in `Samples/tutorial/`. The code is the same as `Samples/tutorial/template` but a different `.rml` file is loaded:

``` html
<rml>
<head>
    <link type="text/css" href="index.rcss"/>
    <title>Window</title>
</head>
<body>
    <p>Some text.</p>
    <p>Some other text.</p>
    <select>
        <option>Option 1</option>
        <option>Option 2</option>
    </select>
</body>
</rml>
```

`index.rcss`:

``` css
body {
    font-family: LatoLatin;
    font-weight: normal;
    font-style: normal;
    font-size: 40dp;
    display: block;
}

select, selectvalue, p {
    border-width: 3dp;
    border-color: #fff;
}

div, p
{
    display: block;
}
```

I'm on Linux and uses the GLFW + GL3 backend. The documents shows like this:

![image](https://github.com/user-attachments/assets/a2123bf7-ebd6-42cb-829a-635b60d6295b)

Seems the `select` element doesn't have enough height, and the text is wrapped.

If we use a flexbox for `body`:

``` css
body {
    font-family: LatoLatin;
    font-weight: normal;
    font-style: normal;
    font-size: 40dp;
    display: flex;
    flex-direction: column;
    align-items: center;
}
```

Then it looks like this:

![image](https://github.com/user-attachments/assets/59bdc23b-359e-4e12-88b4-9f7f97a57e90)

The `select` element now has little width.

**Comment by mikke89** [comment]
Hey, and thanks for the easy-to-follow report.

Right, so for the first screenshot. In RmlUi, all elements are completely unstyled out of the box. So you will have to provide your own styles also for input elements. In particular, the `select` element always has an intrinsic size of 128 x 16 pixels. Thus, if you don't set its width and height, this is the size you'll get. With this in mind, the first screenshot looks as expected. The overflowing part is just that the text doesn't fit in this space, so it wraps down. See the [documentation](https://mikke89.github.io/RmlUiDoc/pages/style_guide.html#drop-down-selection-boxes) for more information on how to style these elements.

I looked a bit into the second screenshot. This turned out to be an issue in how we size replaced elements in flexbox column layout. Hopefully, this should now be fixed with the above commit, let me know how it works out for you. This issue is somewhat related to #640, but required a further change.

**Comment by AmaiKinono** [comment]
Thanks for the clear explanation, really appreciate that!

> The `select` element always has an intrinsic size of 128 x 16 pixels.

Yes. That explains the behavior. I've read the style guide, but I'd prefer a solution that does not specify the size in `dp` directly. So my second try is:

``` css
select {
    height: 1.2em;
}

selectvalue, selectbox {
    white-space: nowrap;
}
```

My expectation is:

1. By using the default line height `1.2em`, the `select` box will have the same height as the `p` element (though it would be better if we have `lh` and `rlh` units).
2. By not allowing the text to wrap, the width will be propped up. The result is:

![image](https://github.com/user-attachments/assets/b9a8d4ec-bb6a-41b3-820c-c2064f15d28f)

So 1 is correct, but 2 is wrong. I wonder why this happens.

Also, it would be great if we could determine the size of `select` by its options, like in a browser:

![image](https://github.com/user-attachments/assets/3627d3a2-4d04-432e-ba50-ddafa6bb6578)

`select` is large enough to fit all options even if the shorter one is selected. I don't know RmlUi well so maybe there are some difficulties that I haven't see.

> Hopefully, this should now be fixed with the above commit, let me know how it works out for you.

Yes, I can confirm it works. Much thanks for your work!
