### ISSUE TITLE
Transitions for decorators not supported?

### ISSUE THREAD

**Issue by v-atamanenko** [mikke89/RmlUi#667]
Hello, it would seem that doing this:

```css
.test
{
	decorator: linear-gradient(105deg, #1E1E1E 0%, #1D1D1D 100%);
	transition: 2s decorator linear-in-out;
}

.test:hover
{
	decorator: linear-gradient(105deg, #193233 0%, #192326 100%);
}
```

Makes the element instantly change background after a 2s delay instead of the expected gradual transition. According to the docs, all properties should be supported?
