### ISSUE TITLE
Table columns are overlapped inside flexbox

### ISSUE THREAD

**Issue by AmaiKinono** [mikke89/RmlUi#671]
I've created an example in the `tutorial` directory. The `rml` file:

```html
<rml>
    <head>
        <link type="text/css" href="tutorial.rcss"/>
        <title>Window</title>
    </head>
    <body>
        <table>
            <tr>
                <td>A: </td>
                <td> <input type="text" /> </td>
            </tr>
            <tr>
                <td>B: </td>
                <td> <input type="text" /> </td>
            </tr>
        </table>
    </body>
</rml>
```

The `rcss` file:

```css
body {
    width: 100%;
    height: 100%;
    font-family: "LatoLatin";
    font-size: 36dp;
    /* display: flex; */
    /* flex-direction: column; */
    /* align-items: flex-start; */
}

input.text {
    border: 3dp;
}

/*
 * Below are default styles from https://mikke89.github.io/RmlUiDoc/pages/rml/html4_style_sheet.html so I'm omitting it.
 */
```

The result is correct:

![image](https://github.com/user-attachments/assets/72267714-350b-47ee-8561-2f1bf37a370b)

But if we add `display: flex;` to body style, the table columns are overlapped:

![image](https://github.com/user-attachments/assets/238b69e8-9c26-494d-86a4-03548933750b)

`flex-direction: column;` fixes this, but `align-items: flex-start;` breaks it again.
