### ISSUE TITLE
Error when trying to center div vertically on RmlUi 6.0

### ISSUE THREAD

**Issue by igorsegallafa** [mikke89/RmlUi#678]
After upgrading to RmlUi 6.0 my layout broke and now I can no longer center a div in the middle of the page...

![image](https://github.com/user-attachments/assets/bd652a98-9df7-4474-b839-0a8f5b1747ac)

rml:
```
<body>
<div class="container">
	<div id="login" data-model="login_model" autofocus>
		<div id="inputs">
			<div class="input-group">
				<label>Account Name</label>
				<input id="account-input" type="text" data-value="account"/>
			</div>
			<div class="input-group">
				<label>Password</label>
				<input type="password" data-value="password"/>
			</div>
		</div>
		<div id="buttons">
			<button id="login-button" data-event-click="login">LOGIN</button>
			<button id="exit-button" data-event-click="exit">EXIT</button>
		</div>
	</div>
</div>
</body>
```

rcss:
```
body
{
    font-family: LatoLatin;
    font-size: 18px;
}

.container
{
    width: 100%;
    height: 100%;
}

#login
{
    width: 335px;
    height: 130px;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    margin: auto;
    decorator: gradient( vertical #121717 #222112 );
    border: 1px #c4c087;
    border-radius: 5px;
    opacity: 0.9;
}
```

**Comment by mikke89** [comment]
Hey. I would try setting the top right left bottom properties to auto. Right now, they are kind of having a fight with the width and height you set there. I don't remember who wins or should win this fight :)

Are all divs here in block display? Are you using absolute positioning?

**Comment by igorsegallafa** [comment]
Yes, all divs have block display. Also didn't work set the top right left bottom properties to auto, I got the same result. I tried to set the position to absolute and now I got another issue:

![image](https://github.com/user-attachments/assets/9b7fe5ff-008a-4b75-94d8-3e540da3682f)

**Comment by AmaiKinono** [comment]
Hi. Although I don't know the cause of this problem, I would suggest another way to center an element. We use utility classes to do that. Here's the rcss:

``` css
.v-center
{
    display: flex;
    flex-direction: column;
    min-height: 100%;
}

.v-center-centered
{
    margin-top: auto;
    margin-bottom: auto;
}

.h-center
{
    box-sizing: content-box;
    margin-left: auto;
    margin-right: auto;
}

#login
{
    width: 335px;
    height: 130px;
    decorator: gradient( vertical #121717 #222112 );
    border: 1px #c4c087;
    border-radius: 5px;
    opacity: 0.9;
}
```

The rml:

``` html
<body>
    <div class="v-center">
      <!-- This means it's the centered element of the v-center, and it should h-center its childs. -->
      <div class="v-center-centered h-center">
        <div id="login" autofocus>
          <div id="inputs">
            <div class="input-group">
              <label>Account Name</label>
              <input id="account-input" type="text"/>
            </div>
            <div class="input-group">
              <label>Password</label>
              <input type="password"/>
            </div>
          </div>
          <div id="buttons">
            <button id="login-button">LOGIN</button>
            <button id="exit-button">EXIT</button>
          </div>
        </div>
      </div>
    </div>
  </body>
```

![image](https://github.com/user-attachments/assets/77f784b1-ae7b-44b5-8a93-9917cde0fab0)

The inside of "inputs" div seems to not layout properly, but I guess that's due to font size and that we don't have other rcss rules in your project.

Credit: The above approach comes from a book called *Every Layout*. The class `v-center` is adapted from [The Cover](https://every-layout.dev/layouts/cover/) in it. The class `h-center` (called "The Center" in the book) is paid content, but you can see it's pretty simple. I am not in financial interest with the author, but the book is a good read.
