### ISSUE TITLE
Implement CSS3 basic arithemetic functions

### ISSUE THREAD

**Issue by hyblocker** [mikke89/RmlUi#691]
Implementing CSS3 arithmetic functions would improve one's ability to do dynamic complex layouts using RmlUI (eg dynamically scaling elements based on viewport dimensions). For instance, one could use CSS such as the following:
```css
div#my-cool-div {
    width: calc(100% - 32px); /* We need a constant width of 32px from the right */
}
```

We would have to start with defining a parser to parse the arithmetic grammar properly and likely also implement an expression cache (to avoid evaluating them every frame) whenever possible.

The definition of these arithmetic functions is defined [here](https://www.w3.org/TR/css-values-4/#calc-func).

Is such a feature beyond the scope of this project or not, given it does not aim to implement the entirety of CSS3?
