### ISSUE TITLE
Decorator inheritance / replacing only changed keys

### ISSUE THREAD

**Issue by Paril** [mikke89/RmlUi#700]
When trying to use media queries to change decorators, it seems like a `@decorator` rule completely replaces the other instead of just changing the key that are different;

```
@decorator arrow_left : image
{
    image-src: /gfx/cursor.png;
    image-fit: contain;
}

@media (theme: bg-contain)
{
	@decorator arrow_left : image {
	    image-src: /gfx/cursor-select.png;
	}
}
```

If the theme is set, `image-fit` ends up getting reset. Right now, our menus need several combinations of things (we have three sizing modes and 5 different BG images depending on language), so we need 5 x 3 different lines just to represent all of the different combinations, but being able to do the above would reduce it to 5 + 3.

**Comment by mikke89** [comment]
We do actually have a bit of a hidden feature when it comes to decorators, they actually support inheritance. So you should be able to do this:

```css
@decorator arrow_left_base : image
{
    image-src: /gfx/cursor.png;
    image-fit: contain;
}

@media (theme: bg-contain)
{
	@decorator arrow_left : arrow_left_base {
	    image-src: /gfx/cursor-select.png;
	}
}
```
