### ISSUE TITLE
Font rendering quality regression in 6.0 release (OPENGL2 backend)

### ISSUE THREAD

**Issue by liehun10086** [mikke89/RmlUi#738]
### Environment:

> RmlUI current master branch [30031ba56786dba6159629ff134edd92d6070459] (upgraded from 6.0 dev)
> 
> OPENGL2 rendering backend
> 
> Font size: ≤13px
> 
> OS: Windows 11

### Issue Description:

After upgrading to the latest master branch code, I've observed a regression in font rendering quality when using the OPENGL2 backend. Text appears less "full" and shows visual artifacts (partial missing pixels) at small font sizes (≤13px), particularly noticeable in UI elements.

### Key observations:

- Text strokes appear thinner/more fragmented compared to the dev version

- Issue persists across different font weights (including bold variants)

- Visual degradation is most prominent in small font sizes

### Attachments:

**Before/after comparison screenshots (6.0-dev vs master)**

> Before:
> ![Image](https://github.com/user-attachments/assets/8ce82fd8-480a-4c61-b91e-828d48a29dbe)

> after
> ![Image](https://github.com/user-attachments/assets/cda2bd90-b4ba-4dd8-a5d7-2d423d5ca091)

### Possible Cause Hypothesis:

I suspect this might relate to:

- Reduced font vector initialization size leading to lower-resolution glyph generation

- Insufficient glyph bitmap resolution during texture atlas creation

- Modified anti-aliasing thresholds in small font rendering pipeline

### Test case:

```css
<template name="bug_test" content="content">
	<head>
		<style>
			.test-parent {
				z-index: 100;
				width: 300px;
				height: 200px;
				top: 10%;
				left: 10%;

				position: absolute;

				display: flex;
				flex-direction: column;

				padding: 4px;
				border: 4px black;
				background-color: #333;
			}

			.test-text {
				flex: 1;
				font-weight: 1000;
				font-family: FZDaHei-B02S;
			}
		</style>
	</head>

	<body>
		<div class="test-parent">
			<p class="test-text" style="font-size: 16px">SAMPLE TEXT sample text 16px</p>
			<p class="test-text" style="font-size: 15px">SAMPLE TEXT sample text 15px</p>
			<p class="test-text" style="font-size: 14px">SAMPLE TEXT sample text 14px</p>
			<p class="test-text" style="font-size: 13px">SAMPLE TEXT sample text 13px</p>
			<p class="test-text" style="font-size: 12px">SAMPLE TEXT sample text 12px</p>
			<p class="test-text" style="font-size: 11px">SAMPLE TEXT sample text 11px</p>
			<p class="test-text" style="font-size: 10px">SAMPLE TEXT sample text 10px</p>
			<p class="test-text" style="font-size:  9px">SAMPLE TEXT sample text  9px</p>
		</div>
	</body>
</template>
```

### Expected Behavior:
Consistent text rendering quality matching previous dev version's output

### Could you please clarify:

- Is this a bug in the rendering pipeline, or might it be caused by my implementation?

- Any recommended checks for font configuration specifics?
